import { RuleType } from 'pbl/enums';
import { ISuppliedRuleConfig, RuleConfig } from 'pbl/models';

// tslint:disable-next-line:max-line-length
const configs = `[
   {
      "ruleId":"10",
      "ruleOrder":"10",
      "ruleType":"8",
      "productCode":"972",
      "optionFlags":"1",
      "ruleStrings":[

      ],
      "ruleInts":[
         {
            "min":"21"
         }
      ]
   },
   {
      "ruleId":"26",
      "ruleOrder":"10",
      "ruleType":"4",
      "productCode":"",
      "optionFlags":"0",
      "ruleStrings":[
         "RR"
      ],
      "ruleInts":[

      ]
   },
   {
      "ruleId":"27",
      "ruleOrder":"10",
      "ruleType":"8",
      "productCode":"",
      "optionFlags":"0",
      "ruleStrings":[

      ],
      "ruleInts":[
         {
            "min":"16"
         }
      ]
   },
   {
      "ruleId":"28",
      "ruleOrder":"10",
      "ruleType":"4",
      "productCode":"978",
      "optionFlags":"1",
      "ruleStrings":[
         "R"
      ],
      "ruleInts":[

      ]
   },
   {
      "ruleId":"29",
      "ruleOrder":"10",
      "ruleType":"4",
      "productCode":"972",
      "optionFlags":"1",
      "ruleStrings":[
         "R"
      ],
      "ruleInts":[

      ]
   },
   {
      "ruleId":"30",
      "ruleOrder":"10",
      "ruleType":"4",
      "productCode":"980",
      "optionFlags":"1",
      "ruleStrings":[
         "R"
      ],
      "ruleInts":[

      ]
   },
   {
      "ruleId":"34",
      "ruleOrder":"10",
      "ruleType":"4",
      "productCode":"982",
      "optionFlags":"1",
      "ruleStrings":[
         "R"
      ],
      "ruleInts":[

      ]
   },
   {
      "ruleId":"37",
      "ruleOrder":"10",
      "ruleType":"4",
      "productCode":"",
      "optionFlags":"0",
      "ruleStrings":[
         "VBM1",
         "VBM2",
         "VBM3",
         "PBM1",
         "PBM2",
         "PBM3",
         "PBM4",
         "PBM5"
      ],
      "ruleInts":[

      ]
   },
   {
      "ruleId":"18",
      "ruleOrder":"20",
      "ruleType":"2",
      "productCode":"VBM1",
      "optionFlags":"0",
      "ruleStrings":[
         "PBM1",
         "PBM2",
         "PBM3",
         "PBM4",
         "PBM5",
         "VBM2",
         "VBM3"
      ],
      "ruleInts":[

      ]
   },
   {
      "ruleId":"19",
      "ruleOrder":"20",
      "ruleType":"2",
      "productCode":"VBM2",
      "optionFlags":"0",
      "ruleStrings":[
         "PBM1",
         "PBM2",
         "PBM3",
         "PBM4",
         "PBM5",
         "VBM1",
         "VBM3"
      ],
      "ruleInts":[

      ]
   },
   {
      "ruleId":"20",
      "ruleOrder":"20",
      "ruleType":"2",
      "productCode":"VBM3",
      "optionFlags":"0",
      "ruleStrings":[
         "PBM1",
         "PBM2",
         "PBM3",
         "PBM4",
         "PBM5",
         "VBM1",
         "VBM2"
      ],
      "ruleInts":[

      ]
   },
   {
      "ruleId":"21",
      "ruleOrder":"20",
      "ruleType":"2",
      "productCode":"PBM1",
      "optionFlags":"0",
      "ruleStrings":[
         "PBM2",
         "PBM3",
         "PBM4",
         "PBM5",
         "VBM1",
         "VBM2",
         "VBM3"
      ],
      "ruleInts":[

      ]
   },
   {
      "ruleId":"22",
      "ruleOrder":"20",
      "ruleType":"2",
      "productCode":"PBM2",
      "optionFlags":"0",
      "ruleStrings":[
         "PBM1",
         "PBM3",
         "PBM4",
         "PBM5",
         "VBM1",
         "VBM2",
         "VBM3"
      ],
      "ruleInts":[

      ]
   },
   {
      "ruleId":"23",
      "ruleOrder":"20",
      "ruleType":"2",
      "productCode":"PBM3",
      "optionFlags":"0",
      "ruleStrings":[
         "PBM1",
         "PBM2",
         "PBM4",
         "PBM5",
         "VBM1",
         "VBM2",
         "VBM3"
      ],
      "ruleInts":[

      ]
   },
   {
      "ruleId":"24",
      "ruleOrder":"20",
      "ruleType":"2",
      "productCode":"PBM4",
      "optionFlags":"0",
      "ruleStrings":[
         "PBM1",
         "PBM2",
         "PBM3",
         "PBM5",
         "VBM1",
         "VBM2",
         "VBM3"
      ],
      "ruleInts":[

      ]
   },
   {
      "ruleId":"25",
      "ruleOrder":"20",
      "ruleType":"2",
      "productCode":"PBM5",
      "optionFlags":"0",
      "ruleStrings":[
         "PBM1",
         "PBM2",
         "PBM3",
         "PBM4",
         "VBM1",
         "VBM2",
         "VBM3"
      ],
      "ruleInts":[

      ]
   },
   {
      "ruleId":"5",
      "ruleOrder":"40",
      "ruleType":"2",
      "productCode":"972",
      "optionFlags":"0",
      "ruleStrings":[
         "978"
      ],
      "ruleInts":[

      ]
   },
   {
      "ruleId":"6",
      "ruleOrder":"40",
      "ruleType":"2",
      "productCode":"978",
      "optionFlags":"0",
      "ruleStrings":[
         "972"
      ],
      "ruleInts":[

      ]
   },
   {
      "ruleId":"31",
      "ruleOrder":"50",
      "ruleType":"1",
      "productCode":"980",
      "optionFlags":"0",
      "ruleStrings":[

      ],
      "ruleInts":[

      ]
   },
   {
      "ruleId":"32",
      "ruleOrder":"50",
      "ruleType":"1",
      "productCode":"971",
      "optionFlags":"0",
      "ruleStrings":[

      ],
      "ruleInts":[

      ]
   },
   {
      "ruleId":"33",
      "ruleOrder":"50",
      "ruleType":"1",
      "productCode":"975",
      "optionFlags":"0",
      "ruleStrings":[

      ],
      "ruleInts":[

      ]
   },
   {
      "ruleId":"35",
      "ruleOrder":"50",
      "ruleType":"1",
      "productCode":"982",
      "optionFlags":"0",
      "ruleStrings":[

      ],
      "ruleInts":[

      ]
   },
   {
      "ruleId":"7",
      "ruleOrder":"60",
      "ruleType":"6",
      "productCode":"980",
      "optionFlags":"0",
      "ruleStrings":[

      ],
      "ruleInts":[
         {
            "min":"1",
            "max":"1"
         }
      ]
   },
   {
      "ruleId":"8",
      "ruleOrder":"60",
      "ruleType":"6",
      "productCode":"971",
      "optionFlags":"0",
      "ruleStrings":[

      ],
      "ruleInts":[
         {
            "min":"1",
            "max":"1"
         }
      ]
   },
   {
      "ruleId":"9",
      "ruleOrder":"60",
      "ruleType":"6",
      "productCode":"975",
      "optionFlags":"0",
      "ruleStrings":[

      ],
      "ruleInts":[
         {
            "min":"1",
            "max":"1"
         }
      ]
   },
   {
      "ruleId":"36",
      "ruleOrder":"60",
      "ruleType":"6",
      "productCode":"982",
      "optionFlags":"0",
      "ruleStrings":[

      ],
      "ruleInts":[
         {
            "min":"1",
            "max":"1"
         }
      ]
   },
   {
      "ruleId":"11",
      "ruleOrder":"80",
      "ruleType":"7",
      "productCode":"980",
      "optionFlags":"0",
      "ruleStrings":[

      ],
      "ruleInts":[
         {
            "max":"14"
         }
      ]
   },
   {
      "ruleId":"12",
      "ruleOrder":"80",
      "ruleType":"3",
      "productCode":"980",
      "optionFlags":"0",
      "ruleStrings":[

      ],
      "ruleInts":[
         {
            "max":"149999"
         }
      ]
   },
   {
      "ruleId":"13",
      "ruleOrder":"80",
      "ruleType":"7",
      "productCode":"971",
      "optionFlags":"0",
      "ruleStrings":[

      ],
      "ruleInts":[
         {
            "max":"14"
         }
      ]
   },
   {
      "ruleId":"14",
      "ruleOrder":"80",
      "ruleType":"9",
      "productCode":"971",
      "optionFlags":"0",
      "ruleStrings":[
         "Diesel",
         "Petrol",
         "LPG",
         "Gas",
         "Petrol/Gas",
         "Gas bi fuel"
      ],
      "ruleInts":[

      ]
   },
   {
      "ruleId":"15",
      "ruleOrder":"80",
      "ruleType":"3",
      "productCode":"971",
      "optionFlags":"0",
      "ruleStrings":[

      ],
      "ruleInts":[
         {
            "max":"149999"
         }
      ]
   },
   {
      "ruleId":"16",
      "ruleOrder":"80",
      "ruleType":"9",
      "productCode":"975",
      "optionFlags":"0",
      "ruleStrings":[
         "Diesel"
      ],
      "ruleInts":[

      ]
   },
   {
      "ruleId":"17",
      "ruleOrder":"90",
      "ruleType":"11",
      "productCode":"980",
      "optionFlags":"0",
      "ruleStrings":[

      ],
      "ruleInts":[

      ]
   }
]`;

const ruleConfigs = (<ISuppliedRuleConfig[]>JSON.parse(configs)).map(r => new RuleConfig(r));

export function getRuleByType(type: RuleType) {
	return ruleConfigs.filter(r => r.ruleType === type);
}
