export const globalDataLayer = {
	pageName: '',
	deviceType: '',
	preSelectedCover: '',
	selectedCover: '',
	addedCover: '',
	removedCover: '',
	preSelectedCoverLevel: '',
	selectedCoverLevel: '',
	addedCoverLevel: '',
	removedCoverLevel: '',
	preSelectedCoverType: '',
	selectedCoverType: '',
	addedCoverType: '',
	removedCoverType: '',
	preSelectedCoverExtras: '',
	selectedCoverExtras: '',
	addedCoverExtras: '',
	removedCoverExtras: '',
	initialPaymentFrequency: '',
	paymentFrequency: '',
	initialPrice: {
		annual: '',
		monthly: '',
	},
	price: {
		annual: '',
		monthly: '',
	},
	people: '',
	vehicles: '',
	fieldName: '',
	fieldNameError: '',
	serverError: '',
	paymentDetails: {
		coverStartDate: '',
		paymentMethod: '',
	},
	sectionName: '',
	stepNumberClicked: '',
	stepNameClicked: '',
};
